# Generated by Django 6.0.6 on 2026-07-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='myaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='mycontact_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='myemail',
            new_name='email',
        ),
    ]
