# Generated by Django 6.0.6 on 2026-08-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inquiry_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='middle_name',
        ),
    ]
