# Generated by Django 6.0.6 on 2026-10-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_inquiry_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techstack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='technology_stack',
            field=models.ManyToManyField(to='main.techstack'),
        ),
    ]
